# Generated by Django 4.2.3 on 2023-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Adress_Call_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.TextField(blank=True, null=True)),
                ('Call', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
